"""initial_schema_sessions_intakes_classifications_entities_kb_entries_documents

Revision ID: 6162fa9169d3
Revises: 
Create Date: 2026-08-13 22:06:00.784279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6162fa9169d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('act_name', sa.String(length=200), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('section_text_plain', sa.Text(), nullable=False),
    sa.Column('remedy_forum', sa.Text(), nullable=True),
    sa.Column('limitation_period', sa.String(length=100), nullable=True),
    sa.Column('notice_template_id', sa.String(length=100), nullable=True),
    sa.Column('law_code', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('last_verified_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("law_code IN ('IPC', 'BNS', 'N/A')", name='ck_kb_entries_law_code_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_domain_issue', 'kb_entries', ['domain', 'issue_type'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=False)
    op.create_table('intakes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('char_length(raw_text) <= 2000', name='ck_intakes_text_max_2000'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakes_session_id'), 'intakes', ['session_id'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('intake_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_clarification', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_classifications_confidence_range'),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_intake_id'), 'classifications', ['intake_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('intake_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('kb_entry_id', sa.UUID(), nullable=True),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('signed_url_token', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("tone IN ('request', 'formal')", name='ck_documents_tone_valid'),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_entry_id'], ['kb_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signed_url_token')
    )
    op.create_index(op.f('ix_documents_intake_id'), 'documents', ['intake_id'], unique=False)
    op.create_index(op.f('ix_documents_kb_entry_id'), 'documents', ['kb_entry_id'], unique=False)
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('intake_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_intake_id'), 'entities', ['intake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_intake_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_kb_entry_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_intake_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_classifications_intake_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_intakes_session_id'), table_name='intakes')
    op.drop_table('intakes')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_kb_domain_issue', table_name='kb_entries')
    op.drop_table('kb_entries')
    # ### end Alembic commands ###
