import os
from datetime import date
from typing import Any, List, Dict
from fpdf import FPDF
from fpdf.enums import XPos, YPos

MANDATORY_DISCLAIMER = (
    "DISCLAIMER: This document is generated by an AI legal assistant for informational and drafting purposes only "
    "and does not constitute formal legal advice. Consult a licensed advocate before filing or serving this notice."
)

def sanitize_pdf_text(text: str) -> str:
    if not text:
        return ""
    # Replace Rupee symbol and non-latin1 characters
    text = text.replace("₹", "Rs. ")
    return text.encode("latin-1", "replace").decode("latin-1")

class LegalNoticePDF(FPDF):
    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.multi_cell(0, 4, MANDATORY_DISCLAIMER, align="C")
        self.set_y(-8)
        self.cell(0, 4, f"Page {self.page_no()}", align="C")

def generate_legal_pdf(
    output_path: str,
    tone: str,
    kb_entry: Any,
    entities: List[Dict[str, Any]],
    user_name: str = "[YOUR NAME]",
    user_address: str = "[YOUR ADDRESS]",
    opposing_name: str = "[OPPOSING PARTY NAME]",
    opposing_address: str = "[OPPOSING PARTY ADDRESS]"
) -> str:
    """
    Generates a PDF document for the legal notice/complaint draft.
    Supports 'request' (polite demand) and 'formal_notice' (statutory notice) tones.
    Embeds verbatim KB legal citations and mandatory disclaimer footer.
    """
    pdf = LegalNoticePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=25)

    # Document Header
    pdf.set_font("Helvetica", "B", 14)
    if tone == "request":
        title = f"REQUISITION & REFUND REQUEST NOTICE\nRegarding: {kb_entry.issue_type.replace('_', ' ').title()}"
    else:
        title = f"LEGAL NOTICE FOR DEMAND & REMEDY\nUnder {kb_entry.act_name}"
    
    pdf.multi_cell(0, 8, title, align="C")
    pdf.ln(5)

    # Date line
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Date: {date.today().strftime('%d %B %Y')}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="R")
    pdf.ln(4)

    # Party Information
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "FROM:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, f"{user_name}\nAddress: {user_address}")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "TO (OPPOSING PARTY):", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, f"{opposing_name}\nAddress: {opposing_address}")
    pdf.ln(6)

    # Subject
    pdf.set_font("Helvetica", "B", 11)
    sub_text = f"SUBJECT: {tone.upper().replace('_', ' ')} REGARDING {kb_entry.issue_type.upper().replace('_', ' ')} AT {kb_entry.remedy_forum.upper()}"
    pdf.multi_cell(0, 6, sub_text)
    pdf.ln(4)

    # Salutation
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, "Dear Sir / Madam,", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # Section 1: Statement of Facts
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "1. STATEMENT OF FACTS:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    
    facts_summary = []
    for ent in entities:
        facts_summary.append(f"  - {ent.get('entity_type', 'Fact').title()}: {ent.get('entity_value', '')}")
    
    if facts_summary:
        facts_body = (
            "The undersigned submits the following verified material facts regarding the dispute:\n" +
            "\n".join(facts_summary) + "\n" +
            "Despite repeated verbal and written requests, the grievance remains unresolved."
        )
    else:
        facts_body = (
            "The undersigned hereby states that a dispute has arisen in connection with " +
            f"{kb_entry.issue_type.replace('_', ' ')} under your jurisdiction, causing financial loss and hardship."
        )
    
    pdf.multi_cell(0, 5, sanitize_pdf_text(facts_body))
    pdf.ln(4)

    # Section 2: Statutory Provisions & Applicable Law
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, sanitize_pdf_text(f"2. APPLICABLE LAW & STATUTORY PROVISIONS ({kb_entry.law_code}):"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    
    statute_body = (
        f"Take notice that under {kb_entry.act_name} ({kb_entry.section_number}), the law provides:\n\n"
        f"\"{kb_entry.section_text_plain}\"\n\n"
        f"Remedy Forum: {kb_entry.remedy_forum}\n"
        f"Statutory Limitation Period: {kb_entry.limitation_period}"
    )
    pdf.multi_cell(0, 5, sanitize_pdf_text(statute_body))
    pdf.ln(4)

    # Section 3: Relief Sought & Call to Action
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "3. DEMAND & RELIEF SOUGHT:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)

    if tone == "request":
        demand_body = (
            "You are hereby politely requested to amicably resolve this matter within 15 days from receipt of this communication "
            "by providing full resolution / refund. Failing which, formal legal proceedings may be initiated."
        )
    else:
        demand_body = (
            "You are hereby called upon to comply with your legal obligations within 15 days of service of this notice. "
            f"Failing compliance, legal proceedings will be formally initiated before the {kb_entry.remedy_forum} "
            "at your sole risk, cost, and consequence."
        )

    pdf.multi_cell(0, 5, demand_body)
    pdf.ln(10)

    # Signature Block
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Yours sincerely,", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(10)
    pdf.cell(0, 6, "____________________________", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, f"({user_name})", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Ensure parent dir exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path
