import React, { useState, useEffect } from 'react';
import { 
  ShieldCheck, AlertCircle, Sparkles, Scale, FileText, Download, 
  Send, Globe, CheckCircle2, ChevronRight, Edit3, HelpCircle, UserCheck,
  Clock, MapPin, Copy, Check, RefreshCw, MessageSquare
} from 'lucide-react';

const MANDATORY_DISCLAIMER = "This document is generated by an AI assistant for informational purposes only and does not constitute legal advice. Consult a licensed advocate before taking legal action.";

const SAMPLE_STARTERS = [
  {
    label: "Tenant Deposit",
    text_en: "My landlord in Bangalore is refusing to return my security deposit of ₹45,000 after 2 months of vacating.",
    text_hi: "मकान मालिक मेरी 45,000 रुपये की सिक्योरिटी डिपॉजिट वापस नहीं कर रहा है।"
  },
  {
    label: "Defective Product",
    text_en: "I bought a washing machine for ₹25,000 but it was broken on arrival. Seller is refusing refund or repair.",
    text_hi: "नया वाशिंग मशीन खरीदा पर वो खराब निकला, दुकानदार वापस नहीं ले रहा।"
  },
  {
    label: "Unpaid Salary",
    text_en: "My company has withheld my monthly salary of ₹35,000 for 3 consecutive months without any written reason.",
    text_hi: "कंपनी 3 महीने से मेरी सैलरी नहीं दे रही है और टाल-मटोल कर रही है।"
  },
  {
    label: "Illegal Eviction",
    text_en: "House owner cut off our electricity and water supply without notice to force us to leave.",
    text_hi: "मकान मालिक ने बिना नोटिस दिए पानी और बिजली का कनेक्शन काट दिया।"
  }
];

export default function App() {
  const [lang, setLang] = useState('en'); // 'en' or 'hi'
  const [sessionId, setSessionId] = useState(null);
  
  // Intake state
  const [inputText, setInputText] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Flow State
  const [intakeData, setIntakeData] = useState(null);
  const [classification, setClassification] = useState(null);
  const [entities, setEntities] = useState([]);
  const [kbEntry, setKbEntry] = useState(null);
  
  // Clarification state
  const [manualDomain, setManualDomain] = useState('');
  const [manualIssue, setManualIssue] = useState('');
  
  // Explanation state
  const [explanationData, setExplanationData] = useState(null);
  const [expLoading, setExpLoading] = useState(false);
  const [copiedExp, setCopiedExp] = useState(false);

  // Document state
  const [docTone, setDocTone] = useState('formal_notice');
  const [userName, setUserName] = useState('');
  const [userAddress, setUserAddress] = useState('');
  const [opposingName, setOpposingName] = useState('');
  const [opposingAddress, setOpposingAddress] = useState('');
  const [generatedDoc, setGeneratedDoc] = useState(null);
  const [docLoading, setDocLoading] = useState(false);

  // Chat (RAG) state
  const [chatMessages, setChatMessages] = useState([]);
  const [chatInput, setChatInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);

  // Initialize session
  useEffect(() => {
    fetch('/api/session', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({})
    })
      .then(res => res.json())
      .then(data => setSessionId(data.session_id))
      .catch(err => console.error("Session init failed:", err));
  }, []);

  // Handle Intake submission
  const handleIntakeSubmit = async (e) => {
    e.preventDefault();
    if (!inputText.trim() || !sessionId) return;

    setLoading(true);
    setError(null);
    setExplanationData(null);
    setGeneratedDoc(null);

    try {
      const res = await fetch('/api/intake', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          session_id: sessionId,
          raw_text: inputText,
          language: lang
        })
      });
      const data = await res.json();
      
      setIntakeData(data);
      setClassification(data.classification);
      setEntities(data.entities || []);
      setKbEntry(data.kb_entry);

      if (data.kb_entry) {
        fetchExplanation(data.kb_entry.id, data.entities);
      }
    } catch (err) {
      setError("Failed to process request. Please ensure the backend server is running at http://localhost:8000.");
    } finally {
      setLoading(false);
    }
  };

  // Fetch LLM rephrased explanation
  const fetchExplanation = async (kbId, currentEntities) => {
    setExpLoading(true);
    try {
      const res = await fetch('/api/explanation', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          kb_entry_id: kbId,
          facts: currentEntities
        })
      });
      const data = await res.json();
      setExplanationData(data);
    } catch (err) {
      console.error("Explanation fetch error:", err);
    } finally {
      setExpLoading(false);
    }
  };

  // Handle Manual Domain Override
  const handleManualOverride = async () => {
    if (!intakeData || !manualDomain || !manualIssue) return;
    setLoading(true);
    try {
      const res = await fetch('/api/classify/manual', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          intake_id: intakeData.intake_id,
          domain: manualDomain,
          issue_type: manualIssue
        })
      });
      const data = await res.json();
      
      setClassification(prev => ({ ...prev, domain: manualDomain, issue_type: manualIssue, clarification_needed: false }));
      setKbEntry(data.kb_entry);
      if (data.kb_entry) {
        fetchExplanation(data.kb_entry.id, entities);
      }
    } catch (err) {
      console.error("Manual override error:", err);
    } finally {
      setLoading(false);
    }
  };

  // Copy Explanation
  const handleCopyExplanation = () => {
    const textToCopy = explanationData?.explanation || kbEntry?.plain_summary_seed;
    if (textToCopy) {
      navigator.clipboard.writeText(textToCopy);
      setCopiedExp(true);
      setTimeout(() => setCopiedExp(false), 2000);
    }
  };

  // Handle Document Generation
  const handleGenerateDoc = async () => {
    if (!sessionId || !kbEntry) return;
    setDocLoading(true);
    try {
      const res = await fetch('/api/document/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          session_id: sessionId,
          kb_entry_id: kbEntry.id,
          tone: docTone,
          user_name: userName || (lang === 'hi' ? 'प्रथम नागरिक' : 'First Citizen'),
          user_address: userAddress || (lang === 'hi' ? 'निवासी स्थान' : 'Resident Address'),
          opposing_name: opposingName || (lang === 'hi' ? 'विपक्षी पक्ष' : 'Opposing Party'),
          opposing_address: opposingAddress || (lang === 'hi' ? 'विपक्षी पता' : 'Opposing Address')
        })
      });
      const data = await res.json();
      setGeneratedDoc(data);
    } catch (err) {
      console.error("Document generation error:", err);
    } finally {
      setDocLoading(false);
    }
  };

  // Handle Chat message (RAG)
  const handleSendChatMessage = async (e) => {
    e.preventDefault();
    if (!chatInput.trim() || !sessionId) return;

    const userMsg = { role: 'user', content: chatInput };
    setChatMessages(prev => [...prev, userMsg]);
    const currentQuery = chatInput;
    setChatInput('');
    setChatLoading(true);

    try {
      const res = await fetch(`/api/chat/${sessionId}/message`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: currentQuery,
          domain_hint: classification?.domain
        })
      });
      const data = await res.json();
      setChatMessages(prev => [...prev, {
        role: 'assistant',
        content: data.content,
        source_chunks: data.source_chunks,
        abstained: data.abstained
      }]);
    } catch (err) {
      console.error("Chat error:", err);
    } finally {
      setChatLoading(false);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      
      {/* App Header */}
      <header className="app-header">
        <div className="header-container">
          <div className="logo-group">
            <div className="logo-icon">
              <Scale size={24} />
            </div>
            <div>
              <div className="logo-title">LegalAId</div>
              <div className="logo-subtitle">
                {lang === 'hi' ? 'प्रथम-पीढ़ी के मुकदमों के लिए एआई कानूनी सहायक' : 'AI Legal Rights Assistant for First-Generation Litigants'}
              </div>
            </div>
          </div>

          <div className="nav-actions">
            <div className="tag-badge">
              <ShieldCheck size={14} />
              100% Citation Guard
            </div>

            <button 
              className="lang-btn" 
              onClick={() => setLang(l => l === 'en' ? 'hi' : 'en')}
            >
              <Globe size={16} />
              {lang === 'en' ? 'हिंदी (Devanagari)' : 'English'}
            </button>
          </div>
        </div>
      </header>

      {/* Main Body Grid */}
      <main className={`main-layout ${kbEntry ? 'split-view' : ''}`}>
        
        {/* Left Column: Hero & Case Intake */}
        <div>
          {!kbEntry && (
            <div className="hero-banner">
              <div className="hero-pill">
                <Sparkles size={14} />
                PS-04 Hackathon Edition • Consumer, Labor & Tenant Rights
              </div>
              <h1 className="hero-title">
                {lang === 'hi' 
                  ? 'अपनी कानूनी समस्या अपनी भाषा में कहें' 
                  : 'Empowering Litigants with Guaranteed Legal Rights'}
              </h1>
              <p className="hero-subtitle">
                {lang === 'hi'
                  ? 'सत्यापित कानूनी धाराएं प्राप्त करें और अदालत/प्राधिकरण के लिए तुरंत कानूनी नोटिस डाउनलोड करें।'
                  : 'Deterministic knowledge lookup guarantees 100% citation accuracy without hallucinating statute numbers.'}
              </p>
            </div>
          )}

          {/* Case Intake Card */}
          <div className="glass-card intake-box">
            <div className="intake-header">
              <h2 style={{ fontSize: '1.2rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.6rem', color: '#f8fafc' }}>
                <Edit3 size={20} color="#3b82f6" />
                {lang === 'hi' ? 'मामले का विवरण दर्ज करें' : 'Describe Your Legal Issue'}
              </h2>
              <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                {lang === 'hi' ? 'हिंदी या अंग्रेजी में लिखें' : 'Bilingual Support (English / Devanagari)'}
              </span>
            </div>

            {/* Quick Sample Starter Chips */}
            <div>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '0.4rem', fontWeight: 600 }}>
                {lang === 'hi' ? 'त्वरित उदाहरण चुनें:' : 'Quick Sample Prompts:'}
              </div>
              <div className="prompt-starters">
                {SAMPLE_STARTERS.map((starter, i) => (
                  <button
                    key={i}
                    type="button"
                    className="starter-chip"
                    onClick={() => setInputText(lang === 'hi' ? starter.text_hi : starter.text_en)}
                  >
                    <ChevronRight size={12} color="#3b82f6" />
                    {starter.label}
                  </button>
                ))}
              </div>
            </div>

            <form onSubmit={handleIntakeSubmit}>
              <textarea
                className="intake-textarea"
                placeholder={
                  lang === 'hi'
                    ? "उदाहरण: मेरा मकान मालिक पिछले 2 महीने से मेरा 45,000 रुपये का सिक्योरिटी डिपॉजिट वापस नहीं कर रहा है..."
                    : "Example: My landlord is refusing to return my security deposit of ₹45,000 after I vacated the flat..."
                }
                value={inputText}
                onChange={e => setInputText(e.target.value)}
              />

              <div className="intake-actions" style={{ marginTop: '1rem' }}>
                <button 
                  type="submit" 
                  className="btn-primary"
                  disabled={loading || !inputText.trim()}
                >
                  {loading ? (
                    <>
                      <RefreshCw size={18} className="animate-spin" />
                      {lang === 'hi' ? 'विश्लेषण जारी है...' : 'Analyzing Case Facts...'}
                    </>
                  ) : (
                    <>
                      <Sparkles size={18} />
                      {lang === 'hi' ? 'कानूनी अधिकार खोजें' : 'Analyze Legal Rights'}
                    </>
                  )}
                </button>

                {classification && (
                  <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', fontSize: '0.82rem' }}>
                    <span style={{ background: 'rgba(59, 130, 246, 0.15)', border: '1px solid rgba(59, 130, 246, 0.3)', padding: '0.2rem 0.6rem', borderRadius: '4px', color: '#60a5fa', fontWeight: 600 }}>
                      {classification.domain.toUpperCase()}
                    </span>
                    <span style={{ background: 'rgba(16, 185, 129, 0.15)', border: '1px solid rgba(16, 185, 129, 0.3)', padding: '0.2rem 0.6rem', borderRadius: '4px', color: '#34d399', fontWeight: 600 }}>
                      {classification.issue_type}
                    </span>
                  </div>
                )}
              </div>
            </form>

            {error && (
              <div className="warning-box">
                <AlertCircle size={18} />
                <span>{error}</span>
              </div>
            )}
          </div>



          {/* Extracted Facts Review Box */}
          {entities.length > 0 && (
            <div className="glass-card result-card" style={{ marginTop: '1.5rem' }}>
              <div className="card-header">
                <div className="card-title">
                  <UserCheck size={20} color="#10b981" />
                  {lang === 'hi' ? 'निकाले गए मुख्य तथ्य (सत्यापित करें)' : 'Extracted Case Facts'}
                </div>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Auto-extracted by NER</span>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '0.75rem' }}>
                {entities.map((ent, idx) => (
                  <div key={idx} style={{ background: 'rgba(15, 23, 42, 0.9)', padding: '0.75rem 0.9rem', borderRadius: '10px', border: '1px solid var(--border-color)' }}>
                    <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 600, letterSpacing: '0.04em' }}>
                      {ent.entity_type}
                    </div>
                    <div style={{ fontWeight: 700, fontSize: '1rem', color: '#60a5fa', marginTop: '0.2rem' }}>
                      {ent.entity_value}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Right Column: Structured 3-Card Results Grid */}
        {kbEntry && (
          <div className="cards-grid">
            
            {/* Card 1: Plain-Language Legal Rights Explanation */}
            <div className="glass-card result-card" style={{ borderLeft: '4px solid var(--accent-blue)' }}>
              <div className="card-header">
                <div className="card-title">
                  <Sparkles size={22} color="#3b82f6" />
                  {lang === 'hi' ? 'आपके कानूनी अधिकार' : 'Your Verified Legal Rights'}
                </div>
                <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
                  <button 
                    onClick={handleCopyExplanation} 
                    className="btn-secondary"
                    style={{ padding: '0.35rem 0.65rem', fontSize: '0.78rem', display: 'flex', gap: '0.3rem', alignItems: 'center' }}
                  >
                    {copiedExp ? <Check size={14} color="#34d399" /> : <Copy size={14} />}
                    {copiedExp ? 'Copied' : 'Copy'}
                  </button>
                  <span className="badge badge-verified">
                    <ShieldCheck size={14} />
                    Verified Citation
                  </span>
                </div>
              </div>

              {expLoading ? (
                <div>
                  <div className="skeleton-line" style={{ width: '100%' }}></div>
                  <div className="skeleton-line" style={{ width: '85%' }}></div>
                  <div className="skeleton-line" style={{ width: '60%' }}></div>
                </div>
              ) : (
                <div style={{ fontSize: '1.02rem', lineHeight: '1.65', color: '#e2e8f0', background: 'rgba(15, 23, 42, 0.5)', padding: '1rem', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.05)' }}>
                  {explanationData?.explanation || kbEntry.plain_summary_seed}
                </div>
              )}

              <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', display: 'flex', justifyContent: 'space-between', borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: '0.6rem' }}>
                <span>Source: Deterministic Knowledge Base</span>
                <span>Citation Guard: <strong style={{ color: '#34d399' }}>PASSED</strong></span>
              </div>
            </div>

            {/* Card 2: Applicable Law & Forum */}
            <div className="glass-card result-card" style={{ borderLeft: '4px solid var(--accent-emerald)' }}>
              <div className="card-header">
                <div className="card-title">
                  <Scale size={22} color="#10b981" />
                  {lang === 'hi' ? 'लागू कानून और धाराएं' : 'Applicable Statute & Forum'}
                </div>
                <span className="badge" style={{ background: 'rgba(16, 185, 129, 0.15)', color: '#34d399', border: '1px solid rgba(16, 185, 129, 0.4)' }}>
                  {kbEntry.law_code || 'Statutory Code'}
                </span>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                <div className="info-row">
                  <span className="info-label">Statute Act</span>
                  <span className="info-value" style={{ color: '#93c5fd' }}>{kbEntry.act_name}</span>
                </div>
                <div className="info-row">
                  <span className="info-label">Section Citation</span>
                  <span className="info-value" style={{ color: '#f472b6', fontFamily: 'monospace' }}>{kbEntry.section_number}</span>
                </div>
                <div className="info-row">
                  <span className="info-label">Remedy Forum</span>
                  <span className="info-value" style={{ color: '#fcd34d', display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                    <MapPin size={14} />
                    {kbEntry.remedy_forum}
                  </span>
                </div>
                <div className="info-row">
                  <span className="info-label">Limitation Period</span>
                  <span className="info-value" style={{ color: '#fb923c', display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                    <Clock size={14} />
                    {kbEntry.limitation_period}
                  </span>
                </div>
              </div>

              {/* Limitation Notice Warning */}
              <div className="limitation-box">
                <Clock size={18} style={{ flexShrink: 0, marginTop: '2px' }} />
                <span>
                  <strong>Limitation Warning:</strong> Your claim must be formally submitted within <strong>{kbEntry.limitation_period}</strong>. Prompt written notice is strongly advised.
                </span>
              </div>
            </div>

            {/* Card 3: Actionable Notice Generation */}
            <div className="glass-card result-card" style={{ borderLeft: '4px solid var(--accent-purple)' }}>
              <div className="card-header">
                <div className="card-title">
                  <FileText size={22} color="#a855f7" />
                  {lang === 'hi' ? 'कानूनी नोटिस ड्राफ्ट तैयार करें' : 'Generate Legal Notice PDF'}
                </div>
                <span style={{ fontSize: '0.8rem', color: '#c084fc', fontWeight: 600 }}>Ready to Print</span>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                <div className="form-group">
                  <label className="form-label">Notice Style Tone:</label>
                  <div className="tone-selector">
                    <button 
                      type="button"
                      className={`tone-pill ${docTone === 'request' ? 'active' : ''}`}
                      onClick={() => setDocTone('request')}
                    >
                      Polite Requisition Notice
                    </button>
                    <button 
                      type="button"
                      className={`tone-pill ${docTone === 'formal_notice' ? 'active' : ''}`}
                      onClick={() => setDocTone('formal_notice')}
                    >
                      Formal Statutory Notice
                    </button>
                  </div>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
                  <div className="form-group">
                    <label className="form-label">Your Name (Complainant)</label>
                    <input
                      type="text"
                      placeholder="e.g. Rahul Sharma"
                      className="input-styled"
                      value={userName}
                      onChange={e => setUserName(e.target.value)}
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-label">Opposing Party Name</label>
                    <input
                      type="text"
                      placeholder="e.g. Landlord / Store Manager"
                      className="input-styled"
                      value={opposingName}
                      onChange={e => setOpposingName(e.target.value)}
                    />
                  </div>
                </div>

                <button 
                  className="btn-primary" 
                  onClick={handleGenerateDoc}
                  disabled={docLoading}
                  style={{ background: 'linear-gradient(135deg, #9333ea, #db2777)', justifyContent: 'center' }}
                >
                  {docLoading ? (
                    <>
                      <RefreshCw size={18} className="animate-spin" />
                      Generating Legal PDF...
                    </>
                  ) : (
                    <>
                      <FileText size={18} />
                      Generate & Download Legal Notice PDF
                    </>
                  )}
                </button>

                {generatedDoc && (
                  <div style={{ background: 'rgba(16, 185, 129, 0.12)', border: '1px solid #10b981', padding: '0.85rem 1rem', borderRadius: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div style={{ fontSize: '0.88rem', color: '#34d399', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                      <CheckCircle2 size={18} />
                      PDF Draft Generated Successfully!
                    </div>
                    <a 
                      href={generatedDoc.download_url} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="btn-primary" 
                      style={{ padding: '0.45rem 0.9rem', fontSize: '0.85rem', background: '#10b981' }}
                    >
                      <Download size={14} /> Download PDF
                    </a>
                  </div>
                )}
              </div>
            </div>

            {/* Follow-up RAG Chat Module */}
            <div className="glass-card chat-container" style={{ borderLeft: '4px solid var(--accent-amber)' }}>
              <div className="card-header" style={{ padding: '1.2rem' }}>
                <div className="card-title" style={{ fontSize: '1.1rem' }}>
                  <MessageSquare size={20} color="#f59e0b" />
                  {lang === 'hi' ? 'अतिरिक्त प्रश्न पूछें (RAG)' : 'Grounded Statute Q&A Chat'}
                </div>
                <span className="badge badge-rag">
                  <Sparkles size={13} />
                  RAG Statute Reference
                </span>
              </div>

              <div className="chat-messages">
                {chatMessages.length === 0 && (
                  <div style={{ textAlign: 'center', color: 'var(--text-muted)', fontSize: '0.88rem', marginTop: '2.5rem' }}>
                    Ask follow-up questions like: <br />
                    <em style={{ color: '#fbbf24' }}>"What if they fail to respond within 15 days?"</em>
                  </div>
                )}
                {chatMessages.map((msg, idx) => (
                  <div key={idx} className={`chat-bubble ${msg.role}`}>
                    <div>{msg.content}</div>
                    {msg.source_chunks && msg.source_chunks.length > 0 && (
                      <div style={{ marginTop: '0.5rem', fontSize: '0.78rem', color: '#fde047', borderTop: '1px dashed rgba(255,255,255,0.15)', paddingTop: '0.3rem' }}>
                        Source: <strong>{msg.source_chunks[0].act_name} ({msg.source_chunks[0].section_number})</strong>
                      </div>
                    )}
                  </div>
                ))}
                {chatLoading && (
                  <div className="chat-bubble assistant" style={{ fontStyle: 'italic', color: 'var(--text-muted)' }}>
                    Searching grounded statute chunks...
                  </div>
                )}
              </div>

              <form onSubmit={handleSendChatMessage} className="chat-input-bar">
                <input
                  type="text"
                  className="chat-input"
                  placeholder="Ask a follow-up statutory question..."
                  value={chatInput}
                  onChange={e => setChatInput(e.target.value)}
                />
                <button type="submit" className="btn-primary" style={{ padding: '0.65rem 1.1rem' }}>
                  <Send size={16} />
                </button>
              </form>
            </div>

          </div>
        )}
      </main>

      {/* Mandatory Disclaimer Footer */}
      <footer style={{ marginTop: 'auto', padding: '1.75rem 1rem', background: '#05070c', borderTop: '1px solid var(--border-color)', textAlign: 'center' }}>
        <div style={{ maxWidth: '960px', margin: '0 auto', fontSize: '0.82rem', color: 'var(--text-muted)', lineHeight: '1.6' }}>
          <strong style={{ color: 'var(--accent-amber)' }}>Mandatory Legal Disclaimer:</strong> {MANDATORY_DISCLAIMER}
        </div>
      </footer>
    </div>
  );
}
